[package]
name = "dog"
description = "A command-line DNS client"

authors = ["Benjamin Sago <ogham@bsago.me>"]
categories = ["command-line-utilities"]
edition.workspace = true
rust-version.workspace = true
exclude = [
    "/completions/*", "/man/*", "/xtests/*", "/tests/*",
    "/dog-screenshot.png", "/Justfile", "/README.md", "/.rustfmt.toml",
]
homepage = "https://dns.lookup.dog/"
license = "EUPL-1.2"
version = "0.2.0-pre"


[[bin]]
name = "dog"
path = "src/main.rs"
doctest = false


[workspace]
members = [
  "dns",
  "dns-transport",
  "test-support",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.87"

[workspace.dependencies]
dns = { path = "dns" }
dns-transport = { path = "dns-transport" }
test-support = { path = "test-support" }
log = "0.4"
pretty_assertions = "1"


# make dev builds faster by excluding debug symbols
[profile.dev]
debug = false

# use LTO for smaller binaries (that take longer to build)
[profile.release]
lto = true
overflow-checks = true
panic = "abort"


[dependencies]

# dns stuff
dns.workspace = true
dns-transport.workspace = true

# command-line
getopts = "0.2"
nu-ansi-term = "0.50"

# transaction ID generation
rand = "0.10"

# json output, keeping keys in the order they are written
serde_json = { version = "1", features = ["preserve_order"] }

# logging
log.workspace = true

# windows default nameserver determination
[target.'cfg(windows)'.dependencies]
ipconfig = "0.3"

[dev-dependencies]
pretty_assertions.workspace = true
test-support = { workspace = true, features = ["tls"] }

[features]
default = ["with_idna", "with_tls", "with_https"]
with_idna = ["dns/with_idna"]
with_tls = ["dns-transport/with_tls"]
with_https = ["dns-transport/with_https"]
