[package]
name = "dns-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
dns = { path = ".." }
libfuzzer-sys = "0.4"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_parsing"
path = "fuzz_targets/fuzz_parsing.rs"
test = false
doc = false
bench = false
