[package]
name = "dns-transport"
version = "0.2.0-pre"
authors = ["Benjamin Sago <ogham@bsago.me>"]
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false


[dependencies]

# dns wire protocol
dns.workspace = true

# logging
log.workspace = true

# tls networking, through the system's TLS library (OpenSSL on Linux)
native-tls = { version = "0.2", optional = true }

# http response parsing
httparse = { version = "1", optional = true }

[dev-dependencies]
test-support = { workspace = true, features = ["tls"] }

[features]
default = []  # these are enabled in the main dog crate

with_tls   = ["dep:native-tls"]
with_https = ["dep:native-tls", "dep:httparse"]
